development:
  adapter: postgresql
  database: congressconnect_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: congressconnect_test
  pool: 5
  timeout: 5000

cucumber:
  <<: *test